name: Publish Docker image

on:
  push:
    branches:
      - uat

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
    
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
           
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Read Version from YAML file
        id: read_ymal
        run: |
            VERSION=$(yq '.version' version.yaml)
            DATETIME=$(date +'%Y%m%d%H%M%S')
            FULL_VERSION="${VERSION}-${DATETIME}"
            echo "version=$FULL_VERSION" >> $GITHUB_OUTPUT


      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      #   with:
      #     images: ${{ secrets.DOCKER_USERNAME }}/test-node-js
      #     tags: |
      #       ${{ steps.vars.outputs.sha_commitID }}

      - name: Pull Docker image
        run: |
          git log -2 --format=%H
          docker pull ${{ secrets.DOCKER_USERNAME }}/test-node-js:$(git log -2 --format=%H | tail -1)
      
      - name: Retag and push image to uat
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/test-node-js:$(git log -2 --format=%H | tail -1) ${{ secrets.DOCKER_USERNAME }}/test-node-js:${{steps.read_ymal.outputs.version}}
          docker push ${{ secrets.DOCKER_USERNAME }}/test-node-js:${{steps.read_ymal.outputs.version}}
    outputs:
      image_tag: ${{ steps.read_ymal.outputs.version }}
      

  trigger_cd_pipeline:
    name: Trigger CD Pipeline
    needs: push_to_registry
    runs-on: self-hosted
    steps:
      # - name: Set up SSH
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_SECRET }}" > ~/.ssh/id_ed25519
      #     chmod 600 ~/.ssh/id_ed25519
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Check out Repo CD
        uses: actions/checkout@v4
        with:
          repository: Aorakin/test-github-cd
          ssh-key: ${{ secrets.SSH_SECRET }}
      
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      # - name: Clone repository
      #   run: |
      #     git clone git@github.com:Aorakin/test-github-cd.git
      #     cd ./test-github-cd.git/

      - name: Replace .uat.env with new image tag
        run: |
          echo "IMAGE=${{ secrets.DOCKER_USERNAME }}/test-node-js:${{ needs.push_to_registry.outputs.image_tag }}" > ./test-github-front/uat/.uat.env

      - name: Commit and Push
        run: |
          git add ./test-github-front/uat
          git commit -m "Trigger CD from Repo CI"
          git push